### ISSUE TITLE
express deprecated res.send(status, body): Use res.status(status).send(body) instead ..\node_modules\express-pouchdb-replication-stream\index.js:51:13

### ISSUE THREAD

**Issue by ronycohen** [conor-mac-aoidh/express-pouchdb-replication-stream#2]
Hello I have this error : 

```
express deprecated res.send(status, body): Use res.status(status).send(body) instead ..\node_modules\express-pouchdb-replication-stream\index.js:51:13
```

When I call the basic usage : 

```
var express = require('express');
var repStream = require('express-pouchdb-replication-stream');
var app = express();

app.use('/api/couchdb', repStream('http://user:pass@localhost:5984/db'));
```

Thank you for your work.

**Comment by conor-mac-aoidh** [comment]
Hmm, I will look into it. It is likely to be a problem with the pouchdb-replication-stream module - there is no `res.send` in my module:

https://github.com/conor-mac-aoidh/express-pouchdb-replication-stream/blob/master/index.js#L51

**Comment by ronycohen** [comment]
I changed it like that, it's OK now.

```
      //res.send(500, err.message);
      res.status(500).send(err.message);
```

**Comment by conor-mac-aoidh** [comment]
Ah ok, I see what has happened. That line was removed a while ago:

https://github.com/conor-mac-aoidh/express-pouchdb-replication-stream/commit/b15a784a293d47cacef5bf6ae04e43ca5ac15b59

But I must have forgotten to publish it to npm. That is done now.

https://www.npmjs.com/package/express-pouchdb-replication-stream

**Comment by ronycohen** [comment]
OK thank you,
I reinstall it.

**Comment by ronycohen** [comment]
It's OK, I don't have the error anymore.

I installed the last version of pouchDB.

**Comment by conor-mac-aoidh** [comment]
Ok cool, going to close the issue.
